# Generated by Django 5.2.1 on 2025-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplan',
            name='anually_details',
            field=models.TextField(blank=True, help_text='Details for the anually plan', null=True),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='anually_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Anually plan price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='biannual_details',
            field=models.TextField(blank=True, help_text='Details for the biannual plan', null=True),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='biannual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Biannual plan price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='triannual_details',
            field=models.TextField(blank=True, help_text='Details for the triannual plan', null=True),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='triannual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Triannual plan price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('anually', 'Anually'), ('biannual', 'Biannual'), ('triannual', 'Triannual')], default='monthly', max_length=20),
        ),
    ]
