# Generated by Django 5.2.1 on 2025-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_hostingplan_anually_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplan',
            name='anually_details',
        ),
        migrations.RemoveField(
            model_name='hostingplan',
            name='anually_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('biannual', 'Biannual'), ('triannual', 'Triannual')], default='monthly', max_length=20),
        ),
    ]
