# Generated by Django 5.2.1 on 2025-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_remove_hostingplan_anually_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplan',
            name='halfyearly_details',
            field=models.TextField(blank=True, help_text='Details for the half yearly plan', null=True),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='halfyearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Half Yearly plan price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('halfyearly', 'Half Yearly'), ('yearly', 'Yearly'), ('biannual', 'Biannual'), ('triannual', 'Triannual')], default='monthly', max_length=20),
        ),
    ]
