"""
Django settings for dosthost project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eokluyigmoe02-n6rjy0i$1rtdoou1=@&u_#af%shyjfxk9(ga'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hosting',
    'blogs',
    # 'invoicing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Email Configuration (Update with your actual credentials)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Or 'django.core.mail.backends.console.EmailBackend' for testing
EMAIL_HOST = 'smtp.gmail.com'  # Your SMTP server
EMAIL_PORT = 587  # Standard port for TLS
EMAIL_USE_TLS = True  # Use TLS encryption
EMAIL_HOST_USER = 'itsyashchaturvedi@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'gxsnvrkjcisndegn'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'itsyashchaturvedi@gmail.com'  # Default sender for automated emails

ROOT_URLCONF = 'dosthost.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hosting.context_processors.site_logo',
                'hosting.context_processors.footer_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'dosthost.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'OPTIONS': {
        'init_command': 'PRAGMA foreign_keys=ON;',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production
# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Add these to your settings.py
RAZORPAY_KEY_ID = 'rzp_test_VvMmkXzEV8uMbJ'
RAZORPAY_KEY_SECRET = 'iM5Y3aFqrcEG38CHoAcQSYDG'    

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin Penal
JAZZMIN_SETTINGS = {
    "site_title": "Dost Host Admin",
    "site_header": "Dost Host",
    "site_brand": "Dost Host",
    "login_logo": "static/assets/images/brand/ug-black-logo.png",  # Correct: relative to static dir
    "login_logo_dark": "static/assets/images/brand/ug-black-logo.png",  # Correct: relative to static dir
    "site_logo": "static/assets/images/brand/ug-black-logo.png",  # Correct: relative to static dir
    "welcome_sign": "Welcome to Dost Host Admin",
    "copyright": "Utopian Gateway",
    "search_model": ["auth.User", "hosting.Order"],
    
    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/your-repo", "new_window": True},
    ],

    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "timetrackerapp"],

    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "timetrackerapp.Project": "fas fa-project-diagram",
        "timetrackerapp.Task": "fas fa-tasks",
        "timetrackerapp.UserProfile": "fas fa-user-circle",
        "timetrackerapp.Screenshot": "fas fa-camera",
        "timetrackerapp.TimeTracking": "fas fa-clock",
    },

    # UI Tweaks
    "custom_links": {
        "timetrackerapp": [{
            "name": "Make Messages", 
            "url": "make_messages", 
            "icon": "fas fa-comments",
            "permissions": ["timetrackerapp.view_project"]
        }]
    },

    "show_ui_builder": True,
    
    # Color scheme
    "theme": "dark",  # or "light"
    
    # Custom CSS
    "custom_css": "admin/css/custom.css",
    "custom_js": "admin/js/custom.js",
}
